In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline
import numpy as np
print(pd.__version__)
print(sns.__version__)
print(np.__version__)

1.4.4
0.12.0
1.23.2

In [4]:
df=pd.read_csv("DataV2/Total.csv",  index_col=0)
df

,18세 미만,18~24세,25~29세,30~34세,35~39세,40~44세,45~49세,50~54세,55~59세,60~64세,...,5인 미만,5~9인,10~19인,20~29인,30~49인,50~99인,100~299인,300~499인,500~999인,1000인 이상
2004,1,50,113,181,256,358,410,348,303,281,...,449,263,330,147,213,229,410,149,166,230
2005,1,31,91,148,230,307,378,336,273,206,...,422,254,247,143,189,210,364,125,154,174
2006,0,33,86,114,179,299,419,342,276,225,...,418,249,255,151,178,215,329,116,173,154
2007,1,30,68,113,203,276,347,331,290,207,...,463,221,207,172,187,203,310,106,133,157
2008,4,29,70,118,190,300,342,343,293,187,...,539,191,229,120,142,253,299,96,140,137
2009,2,31,73,97,148,250,298,303,253,177,...,510,176,194,115,130,174,275,93,130,119
2010,2,34,40,90,122,243,318,321,264,225,...,406,198,227,112,163,224,274,97,101,129
2011,3,30,50,86,121,183,269,346,277,217,...,455,193,212,115,157,183,227,90,113,115
2012,2,24,46,103,123,209,265,274,301,229,...,422,238,232,106,160,168,261,77,87,113
2013,2,29,48,74,105,196,241,347,312,251,...,446,182,200,129,159,200,262,111,112,128
2014,2,35,39,66,100,159,244,283,325,248,...,422,189,211,104,152,174,239,131,122,106
2015,1,35,43,53,103,176,238,271,275,245,...,421,198,187,103,153,177,239,128,123,81
2016,1,21,29,40,93,165,233,263,314,273,...,412,194,201,120,150,172,216,115,114,83
2017,0,15,45,48,96,166,229,290,329,296,...,416,223,244,115,150,190,245,106,177,91
2018,2,31,42,57,92,164,234,325,362,345,...,479,224,249,150,183,170,295,136,153,103
2019,0,19,46,56,100,140,228,267,337,298,...,494,221,260,120,150,180,240,113,158,84
2020,0,14,41,63,80,132,206,295,315,367,...,500,228,248,146,181,160,260,93,162,84
2021,0,20,31,45,95,129,203,312,302,335,...,567,234,250,156,152,174,210,88,141,108